CREATE DATABASE TIEMNGUA1
GO
USE TIEMNGUA1
GO


CREATE TABLE KHACH_HANG
(
	MAKH CHAR(10),
	HOTEN NVARCHAR(30),
	GIOITINH NVARCHAR(5),
	NGSINH DATE,
	DIACHI NVARCHAR(50),
	DIENTHOAI CHAR(10)
	PRIMARY KEY (MAKH)
)

CREATE TABLE NHAN_VIEN
(
	MANV CHAR(10),
	HOTEN NVARCHAR(10), 
	NGSINH DATE,
	DIACHI NVARCHAR(50),
	EMAIL NVARCHAR(30),
	LUONG BIGINT,
	DIENTHOAI CHAR(10),
	BANGCAP NVARCHAR(20),
	VITRI NVARCHAR(20),
	TRUNGTAM NVARCHAR(50),
	PRIMARY KEY (MANV)
)

CREATE TABLE VACXIN
(
	MAVX CHAR(10),
	TENVACXIN NVARCHAR(50),
	GIATIEN BIGINT,
	SOLUONG INT,
	PRIMARY KEY (MAVX)
)

CREATE TABLE GOITIEMCHUNG
(
	MAGTC CHAR(10),
	TENGOITIEM NVARCHAR(50),
	GIATIEN BIGINT,
	MOTA NVARCHAR(200),
	PRIMARY KEY (MAGTC)
)

CREATE TABLE CT_GOITIEMCHUNG
(
	MAGTC CHAR(10),
	MAVX CHAR(10),
	PRIMARY KEY (MAGTC,MAVX)
)

ALTER TABLE CT_GOITIEMCHUNG ADD CONSTRAINT CT_GOITIEMCHUNG_VACXIN FOREIGN KEY (MAVX) REFERENCES VACXIN,
                                CONSTRAINT CT_GOITIEMCHUNG_GTC FOREIGN KEY (MAGTC) REFERENCES GOITIEMCHUNG
CREATE TABLE HOADON
(
	MAHD CHAR(10),
	MAKH CHAR(10),
	MANV CHAR(10),
	MAPHIEUDK char(10),
	TONGTIEN BIGINT,
	SOTIENDADONG BIGINT,
	PPTHANHTOAN NVARCHAR(10),
	NGAYTHANHTOAN DATE,
	TRANGTHAI BIT, 
	PRIMARY KEY (MAHD)
)



CREATE TABLE NHACUNGCAP
(
	MANCC CHAR(10),
	TENNCC NVARCHAR(10),
	SDT CHAR(10)
	PRIMARY KEY (MANCC)
)

CREATE TABLE PHIEUDANGKYTIEMCHUNG
(
	MADK CHAR(10),
	MAKH CHAR(10),
	DUOCTIEM bit,
	DATIEM bit,
	THOIGIANTIEM DATETIME,
	PRIMARY KEY (MADK)
)
ALTER TABLE PHIEUDANGKYTIEMCHUNG ADD CONSTRAINT FK_PHIEUDANGKY FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)

CREATE TABLE CT_DANGKI_VACXIN
(
	MADK CHAR(10),
	MAVX CHAR(10),
	PRIMARY KEY (MADK,MAVX)
)
ALTER TABLE CT_DANGKI_VACXIN ADD CONSTRAINT CT_DANGKI_VACXIN_VACXIN FOREIGN KEY (MAVX) REFERENCES VACXIN,
                      CONSTRAINT FK_CT_DK FOREIGN KEY (MADK) REFERENCES PHIEUDANGKYTIEMCHUNG
CREATE TABLE CT_DANGKI_GOITIEM
(
	MADK CHAR(10),
	MAGTC CHAR(10),
	PRIMARY KEY (MADK,MAGTC)
)
ALTER TABLE CT_DANGKI_GOITIEM ADD CONSTRAINT CT_DANGKI_GOITIEM_VACXIN1 FOREIGN KEY (MADK) REFERENCES PHIEUDANGKYTIEMCHUNG,
                      CONSTRAINT FK_CT_DK_GOITIEM FOREIGN KEY (MAGTC) REFERENCES GOITIEMCHUNG

CREATE TABLE DATMUA
(
	MADM CHAR(10),
	MAKH CHAR(10),
	HOTEN NVARCHAR(50),
	SDT CHAR(10),
	TENDATMUA NVARCHAR(100),
	TRANGTHAI BIT,
	PRIMARY KEY (MADM)
)
ALTER TABLE DATMUA ADD CONSTRAINT DATMUA_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACH_HANG

CREATE TABLE PHIEU_DAT_HANG
(
	MAPDH CHAR(10),
	NHACC CHAR(10),
	TENHANGDAT NVARCHAR(50),
	SOLUONG INT,
	NGAYDATHANG DATE,
	TRANGTHAI INT,
	MANVDUYET CHAR(10)
	PRIMARY KEY (MAPDH)
)

ALTER TABLE PHIEU_DAT_HANG ADD CONSTRAINT PHIEUDATHANG_NCC FOREIGN KEY (NHACC) REFERENCES NHACUNGCAP,
                               CONSTRAINT PHIEUDATHANG_NHANVIEN FOREIGN KEY (MANVDUYET) REFERENCES NHAN_VIEN


CREATE TABLE LICHTRUC
(
	MANV CHAR(10),
	NGAYLAMVIEC DATE,
	CALAMVIEC INT,
	DADUOCDUYET BIT,
	TRUNGTAM NVARCHAR(50)
	PRIMARY KEY (MANV,NGAYLAMVIEC,CALAMVIEC)
)
ALTER TABLE LICHTRUC ADD CONSTRAINT LICHTRUC_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHAN_VIEN
CREATE TABLE NGUOIGIAMHO
(
	MAKH CHAR(10),
	HOTEN NVARCHAR(50),
	SDT CHAR(10),
	MOIQUANHE NVARCHAR(50)
	PRIMARY KEY (MAKH)
)
ALTER TABLE NGUOIGIAMHO ADD CONSTRAINT FK_NGH_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHACH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHAN_VIEN
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_PDANGKY FOREIGN KEY (MAPHIEUDK) REFERENCES PHIEUDANGKYTIEMCHUNG(MADK)

go
alter table hoadon
drop COLUMN sotiendadong

GO
ALTER TABLE HOADON
ADD TRAGOP BIT

go
create table CT_HoaDon
(
	MAHD CHAR(10),
	TIENDONGLAN1 BIGINT,
	NGAYDONGLAN1 DATE,
	TINHTRANGLAN1 BIT,
	TIENDONGLAN2 BIGINT,
	NGAYDONGLAN2 DATE,
	TINHTRANGLAN2 BIT,
	TIENDONGLAN3 BIGINT,
	NGAYDONGLAN3 DATE,
	TINHTRANGLAN3 BIT,
	PRIMARY KEY (MAHD)
)

GO

ALTER TABLE CT_HOADON
ADD CONSTRAINT CT_HOADON_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON
GO
